# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: stack-validation
  name: test-cpupower
  labels:
    app.kubernetes.io/name: test-cpupower
    app.kubernetes.io/component: test-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-cpupower
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-cpupower
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: test-cpupower
        image: rockylinux:9
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 500Mi
        env:
        - name: https_proxy
          #value: "http://yourProxyFQDNOrIP:port"
        command: [ "sh", "-c" ]
        # checks CPU frequency and C-state
        args:
        - dnf install -y cpupowerutils 1>> /dev/null 2>> /dev/null;
          cpussamehwfreq=` cpupower frequency-info 2>> /dev/null | grep "CPUs which run at the same hardware frequency" | awk -vFS=":" ' { print $2 } ' | awk '{gsub(/[ \t]+/, ""); print}' `;
          echo "cpussamehwfreq=${cpussamehwfreq}";
          sleep infinity;
        #securityContext:
          #runAsNonRoot: true
          #runAsUser: 65432
          #runAsGroup: 65432
          #allowPrivilegeEscalation: false
          #capabilities:
          #  drop:
          #    - ALL
          #seccompProfile:
          #  type: RuntimeDefault
          #readOnlyRootFilesystem: true
      #volumes:
      #- name: libmodules
      #  hostPath:
      #    path: /lib/modules
      #    type: Directory
