# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: stack-validation
  name: test-kernelrt
  labels:
    app.kubernetes.io/name: test-kernelrt
    app.kubernetes.io/component: test-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test-kernelrt
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-kernelrt
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: test-kernelrt
        image: alpine:3.20
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: https_proxy
          #value: "http://yourProxyFQDNOrIP:port"
        command: [ "sh", "-c" ]
        # checks kernel
        args:
        - unamerv=` uname -rv `;
          syskernelrealtime=-1;
          if [ -e /sys/kernel/realtime ]; then
            syskernelrealtime=` cat /sys/kernel/realtime `;
          fi;
          proccmdline=` cat /proc/cmdline `;
          echo "unamerv=${unamerv}";
          echo "syskernelrealtime=${syskernelrealtime}";
          echo "proccmdline=${proccmdline}";
          sleep infinity;
        securityContext:
          runAsNonRoot: true
          runAsUser: 65432
          runAsGroup: 65432
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
          readOnlyRootFilesystem: true
